target("NanoC_Compiler")
    set_languages("cxx11")
    set_kind("binary")
    add_files("src/*.cpp")
    -- set_optimize("aggressive")
    set_optimize("smallest")
    add_cxxflags("/Za", {tools = {"clang_cl", "cl"}})
